### ISSUE TITLE
Error Running Dry Run

### ISSUE THREAD

**Issue by kicks88** [ASK-ME-ABOUT-LOOM/purgeomatic#8]
Python V3.11

Tried using localhost or ip via the .env as well as testing it through docker but both ways showing same error even when trying to run  delete.movies.unwatched.py.

Any help or advice would be appreciated.

```
python delete.tv.unwatched.py
DRY_RUN enabled!
--------------------------------------
2023-09-29T00:02:48.434880
Traceback (most recent call last):
  File "/home/seed/purgeomatic/delete.tv.unwatched.py", line 93, in <module>
    shows = json.loads(r.text)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ASK-ME-ABOUT-LOOM** [comment]
That error means that the `shows` variable isn't getting content as expected when the script tries to query tautulli. Odds are that you've got a syntax error in your .env file, an incorrect tautulli API key/connection string, or an incorrect section ID set.

**Comment by kicks88** [comment]
I seem to have resolved it, thank you!
